# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Test E-Commerce Application

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    name: Build and Test Go Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Go Source Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    # Run build on the code
    - name: Build
      env:
          GOPROXY: "https://proxy.golang.org"
      run: go build -v cmd/main.go

    # Run test cases on the code
    - name: Run Test Cases
      run: make test


    # Run go vet on the code
    - name: Check go vet
      run: go vet ./...

    # Run gofmt on the code
    - name: Check Formatting using go fmt
      run: |
            gofmt -s -l .
            if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

    # Run go lint on the code
    - name: Run go lint
      run: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

            golangci-lint run
